### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by BabaYara** [nuffe/wrdsr#1]
Hello Erik,

Thanks for putting together this wonderful package and the ongoing work to maintain it. I am currently trying to connect to wrds via a university network (Eduroam) but I keep getting the following error:

_**"Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLException: Sharenet.S58.ex.txt: Sharenet.S273.ex.txt: Driver could not open socket. Server: wrds-cloud.wharton.upenn.edu port: 8551. Connection timed out: connect."**_

which I believe may be coming from restrictions on my network. Are you aware of any way I can work around this restriction? 
When I tether my phone internet connection to the laptop, everything works smoothly so it is definitely a network issue. 

Hope to get some feedback on the way forward, thank you.
Fahiz

**Comment by nuffe** [comment]
Hi Baba, I am sorry for the late reply.

It turns out this happens on eduroam for me as well. It seems eduroam port restrictions are the problem, SSH'ing to wrds doesn't work either:

```
erik Documents$ ssh erikf@wrds-cloud.wharton.upenn.edu
ssh: connect to host wrds-cloud.wharton.upenn.edu port 22: Operation timed out
```
I guess you can make it work on your own by tunnelling (for example connecting to wrds through a free Amazon AWS server). If you google this there are many guides

**Comment by BabaYara** [comment]
Yeah, in the end I came to the same conclusion. I ended up using a bandwidth limited VPN called betternet. 
All is well now. 

Thank you for the feedback

**Comment by nuffe** [comment]
Glad you worked it out!
